---
- name: Clone the repo
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    version: "{{ git_ref }}"
    dest: "{{ git_clone_dir }}"
    force: yes

- name: Install scraper from directory
  ansible.builtin.pip:
    name: "file://{{ git_clone_dir }}/api/"
    virtualenv: "{{ git_clone_dir }}/.venv"

- name: Run scraper every specified period
  ansible.builtin.cron:
    name: "Run qcraft-scraper"
    minute: "{{ srv_scraper_cron.minute }}"
    job: ". {{ git_clone_dir }}/.venv/bin/activate; . /etc/default/minecraft; qcraft-scraper"
  when: srv_scraper_cron_enable
