---
- name: Build LiveAtlas app
  delegate_to: localhost
  become: no
  connection: local
  ansible.builtin.shell:
    cmd: npm run build
    chdir: "{{ playbook_dir }}/../upstream/liveatlas"
    creates: "{{ playbook_dir }}/../upstream/liveatlas/dist/"
  notify:
    - deploy_liveatlas

- name: List all unecessary web files for removal
  ansible.builtin.find:
    paths: "{{ web_root_dir }}/atlas"
    recurse: no
    file_type: file
    patterns: '*.php,*.aspx,robots.txt,login.html'
  register: web_dynmap_php_files
  notify:
    - clean_web_root

- name: Ensure web directories exist
  become: yes
  loop: "{{ web_dirs }}"
  ansible.builtin.file:
    path: "{{ web_root_dir }}/{{ item }}/"
    state: directory
    owner: "{{ srv_user }}"
    group: "{{ srv_user }}"
    mode: '0755'
  vars:
    web_dirs:
      - "app"
      - "api/v1"

- name: Build web app
  delegate_to: localhost
  become: no
  connection: local
  ansible.builtin.shell:
    cmd: npm run build
    chdir: "{{ playbook_dir }}/../web"
    creates: "{{ playbook_dir }}/../web/dist/"
  notify:
    - deploy_app

- name: Remount dynmap web folder in case overlay was rebuilt
  become: yes
  block:
    - name: Unmount web bind volume
      ansible.posix.mount:
        path: "{{ web_root_dir }}/atlas/"
        src: "{{ srv_overlay_dir }}/plugins/dynmap/web"
        opts: bind
        state: unmounted
        fstype: none
    - name: Mount web bind volume
      ansible.posix.mount:
        path: "{{ web_root_dir }}/atlas/"
        src: "{{ srv_overlay_dir }}/plugins/dynmap/web"
        opts: bind
        state: mounted
        fstype: none
  when: overlay_remounted is defined
