---
- name: Update system packages and configs
  hosts: all
  collections:
    - ansible.posix
    - community.general
  tasks:
    - name: Install packages from repository
      loop: "{{ packages }}"
      become: yes
      ansible.builtin.package:
        state: present
        name: "{{ item }}"
      vars:
        packages:
          - nginx-mainline
          - jre16-openjdk-headless
          - tmux
          - s-tui
          - cronie
          - python-pip
          - certbot

    - name: Install virtualenv
      become: yes
      ansible.builtin.pip:
        name: virtualenv
