---
- name: System config
  ansible.builtin.import_playbook: play_system.yml

- name: Configure Minecraft server and plugins
  ansible.builtin.import_playbook: play_minecraft.yml

- name: Configure Web server
  ansible.builtin.import_playbook: play_webserver.yml

- name: Configure Scraper
  ansible.builtin.import_playbook: play_scraper.yml
